spring.application.name=Manga-Monitor
spring.main.web-application-type=none
spring.datasource.url=jdbc:sqlite:manga-monitor.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
loglevel=TRACE